image_parameters:
  height_og: 1080
  img_path: ./static_frame_from_video.jpg
  l1:
  - 102
  - 1047
  l2:
  - 880
  - 1048
  p1:
  - 10
  - 1214
  p2:
  - 164
  - 903
  p3:
  - 1072
  - 1260
  p4:
  - 750
  - 903
  size_height: 640
  size_width: 352
  width_og: 1920
