image_parameters:
  height_og: 352
  img_path: ./static_frame_from_video.jpg
  l1:
  - 13
  - 519
  l2:
  - 319
  - 520
  p1:
  - 4
  - 613
  p2:
  - 20
  - 410
  p3:
  - 346
  - 614
  p4:
  - 292
  - 416
  size_height: 640
  size_width: 352
  width_og: 640
